#!/usr/bin/python

import re
import sys
import string

def usage():
	print "This is a python script for srt file synchronization."
	print "Four (4) arguments are needed and have to be suplied in the following order:"
	print "1) input file"
	print "2) output file"
	print "3) title number offset (integer; shifts all subtitle numbers by - the given number)"
	print "4) time offset in millis (integer; translates all subtitles by + the given time in milliseconds)"
	print

def new_timetag(timetag):
	new_time = int(timetag.group(1))*3600000 + int(timetag.group(2))*60000 \
		+ int(timetag.group(3))*1000 + int(timetag.group(4)) + time_offset
	new_hours = new_time/3600000
	new_time -= new_hours*3600000
	new_minutes = new_time/60000
	new_time -= new_minutes*60000
	new_seconds = new_time/1000
	new_milis = new_time - new_seconds*1000
	return '{:02d}:{:02d}:{:02d},{:03d}'.format(new_hours,new_minutes,new_seconds,new_milis)

usage()

if len(sys.argv)<5:
	print "ERROR: Too few arguments!"
	sys.exit(-1)
	
title_offset = int(sys.argv[3])
time_offset = int(sys.argv[4])

with open(sys.argv[1],'r') as f_in, open(sys.argv[2],'w') as f_out:

	print "Starting subtitle synchronization..."
		
	for line in f_in:
		#if line doesn't contain '-->' then it is either just a subtitle number or subtitle text
		if re.search(' --> ',line)==None:
			#a line that has only one number is a subtitle ID number
			m = re.match("^[0-9]+$",line.strip())
			if m!=None:
				f_out.write(re.sub('[0-9]+',str(int(m.group(0)) - title_offset),line))
			else:
				f_out.write(line)
		else:
			f_out.write(re.sub('([0-9]{2}):([0-9]{2}):([0-9]{2}),([0-9]{3})',new_timetag,line))

print "Done!"
